- name: install buildbot slave packages
  yum: name={{ item }} state=latest
  with_items:
    - git
    - zanata
    - buildbot-slave
  yum: name=git state=latest
- name: create buildslave user
  user: comment="buildbot slave user" name="buildbot"
- name: Copy buildslave service definition
  copy: src=buildbot-slave@.service dest=/etc/systemd/system/buildbot-slave@.service
  notify: 
    - systemd unit change

# These should be better abstracted later

- name: create directories for buildbot
  file: state=directory path=/srv/buildbot/docs-site/info owner=buildbot group=buildbot
- name: copy buildslave config 
  template: src=buildbot.tac dest=/srv/buildbot/docs-site/buildbot.tac owner=buildbot group=buildbot
  notify:
    - restart buildbot slave

- name: copy buildslave admin info
  copy: src=buildslave-admin-info dest=/srv/buildbot/docs-site/info/admin owner=buildbot group=buildbot
- name: copy buildslave host info
  copy: src=buildslave-host-info dest=/srv/buildbot/docs-site/info/host owner=buildbot group=buildbot
    # need some restart handlers in here
- name: start buildbot slave service
  service: name=buildbot-slave@docs-site enabled=yes state=started

#    Docs specific things
- name: install publican
  yum: name=publican state=latest
- name: install publican brand
  yum: name=publican-fedora state=latest
