- name: Install buildbot master packages.
  yum: name=buildbot-master state=present
- name: Install git
  yum: name=git state=present
- name: create buildslave user
  user: comment="buildbot user" name="buildbot"
- name: Copy buildbot service definition
  copy: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - buildbot-master@.service
    - buildbot-master-creator@.service
  notify: 
    - systemd unit change
- name: open firewall for buildbot web ui
  firewalld: port=8010/tcp permanent=true state=enabled
  notify:
    - firewalld reload
- name: open firewall for buildslave signals
  firewalld: port=9989/tcp permanent=true state=enabled
  notify:
    - firewalld reload
- name: create directories for buildbot
  file: state=directory path=/srv/buildbot/docs-site/info owner=buildbot group=buildbot
- name: deploy buildbot master config
  template: src=master.py dest=/srv/buildbot/docs-site/master.cfg owner=buildbot group=buildbot
  notify:
    - restart buildbot master
