- name: install anerist dependencies
  yum: name={{ item }} state=present
  with_items:
    - python-beautifulsoup4
    - PyYAML
    - python-setuptools    
- name: copy anerist files
  copy: src=../files/anerist dest=/root/
  notify:
    - refresh anerist
